### ISSUE TITLE
(Ruby 3.3.5) Unable to install gem

### ISSUE THREAD

**Issue by vvbogdanov87** [github-community-projects/graphql-client#45]
After upgrading from Ruby 2.7 to Ruby 3.3.5, I can't install my gem, which depends on `graphql-client`.
The error:
```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
```
The issue is similar to the one described here https://github.com/rubygems/rubygems/issues/4338#issuecomment-771493235 One of the dependencies doesn't support Ruby 3.x.
Maybe one of the currently open PRs `chore(deps): *` resolve the issue.

**Comment by rmosolgo** [comment]
Hey, sorry for the trouble! I just merged those dependabot PRs, does that fix it for you?

**Comment by vvbogdanov87** [comment]
@rmosolgo Thanks for the prompt update! It works now.
